language: node_js
node_js:
  - "16"
dist: trusty
sudo: required

branches:
  only:
  - main

before_script:
  - npm install -g @angular/cli
  - npm ci

script:
  - ng lint
  - npm install wait-on
  - npm start & wait-on http://localhost:4200
  - npm run cypress:run
  - ng build --base-href=/TextTools/
