language: node_js
node_js:
  - "16"
dist: trusty
sudo: required

branches:
  only:
  - main

before_script:
  - npm install -g @angular/cli
  - npm ci

script:
  - ng lint
  - ng build --base-href=/TextTools/
