name: Push to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install -g @angular/cli
          npm ci

      - name: ng build
        run: |
          ng lint
          ng deploy --base-href=/TextTools/ --repo=https://github.com/mfcar/TextTools.git --name=texttools --email=$EMAIL --message="Build from ${GITHUB_SHA} in the source repository." --branch=github_page
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
